// <auto-generated />
namespace DocSystDataAccessImplementation.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class init3435 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init3435));
        
        string IMigrationMetadata.Id
        {
            get { return "201805092316543_init3435"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
